#!/usr/bin/env tsx
/**
 * conf-template generator — intent-driven architecture.
 *
 * Pipeline (per region × variant × version):
 *   1. Load `RegionIntent` from `scripts/convention/intent/<region>.ts`.
 *   2. Compile with a version-specific generator (currently all supported
 *      versions share `sing-box-v1-13-8.ts` — 1.12+ all accept its output).
 *   3. Static validate (see `scripts/convention/validator.ts` — enforces
 *      ref integrity, required preamble, tag anchor priority, DNS/route
 *      consistency).
 *   4. Optionally run `sing-box check` on the emitted output (--strict or
 *      SING_BOX_BIN=...). Uses an in-memory patched copy to work around
 *      the empty `auto.outbounds` placeholder OneBox fills at runtime.
 *   5. Write to `conf/<version>/<region>/<variant>.jsonc`.
 *
 * The canonical source of truth is now `scripts/convention/intent/<region>.ts`
 * + `scripts/convention/generator/*.ts`. The generated jsonc files are
 * derived products — hand-editing them is useless, the next `pnpm generate`
 * run overwrites them.
 *
 * Usage:
 *   pnpm generate                 # validate statically, write
 *   pnpm generate:strict          # also run `sing-box check` on each
 *   tsx scripts/generate.ts --dry-run   # validate only, no writes
 */

import { execFileSync } from 'node:child_process';
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { ZH_CN_INTENT } from './convention/intent/zh-cn.js';
import { build as buildSingBoxV1_12 } from './convention/generator/sing-box-v1-12.js';
import { build as buildSingBoxV1_13 } from './convention/generator/sing-box-v1-13.js';
import { build as buildSingBoxV1_13_8 } from './convention/generator/sing-box-v1-13-8.js';
import { ValidationError, validate } from './convention/validator.js';
import type { Region, RegionIntent, SingBoxConfig, Variant, Version } from './convention/types.js';
import { REGIONS, VARIANTS, VERSIONS } from './convention/types.js';

// ---------------------------------------------------------------------------
// Setup
// ---------------------------------------------------------------------------

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(__dirname, '..');

const args = process.argv.slice(2);
const STRICT = args.includes('--strict') || process.env.SING_BOX_BIN !== undefined;
const DRY_RUN = args.includes('--dry-run');

/** Region → intent registry. Add new regions by dropping an entry here. */
const INTENTS: Record<Region, RegionIntent> = {
    'zh-cn': ZH_CN_INTENT,
};

/**
 * Version → generator registry — strictly 1:1 with `conf/<bucket>/`.
 *
 * The rule: **every version bucket has its own generator file, named to
 * match the folder.** Creating a new bucket is itself the signal that
 * some breaking change warrants a separate lineage — even if the new
 * bucket's output is currently byte-identical to the previous one, the
 * files stay separate so the next breaking change touches only the
 * affected bucket, and an older bucket's output never changes because
 * of a feature we added to a newer one.
 *
 * Adding a new version bucket (e.g. `1.13.12`, `1.14`):
 *   1. Create `conf/<ver>/` and add `<ver>` to `VERSIONS` in
 *      `./convention/types.ts`.
 *   2. Copy the most recent generator to `sing-box-v<ver>.ts`.
 *   3. Add the `<ver>` entry below pointing at the new file.
 *   4. Record WHY this bucket forks (what broke, or what feature we're
 *      opting the older buckets out of) in the new file's header comment.
 *
 * Never point two buckets at the same generator — if you're tempted to,
 * you probably don't need the new bucket at all.
 */
const GENERATORS: Record<Version, (intent: RegionIntent, variant: Variant) => SingBoxConfig> = {
    '1.13.8': buildSingBoxV1_13_8,
    '1.13': buildSingBoxV1_13,
    '1.12': buildSingBoxV1_12,
};

// ---------------------------------------------------------------------------
// Output path
// ---------------------------------------------------------------------------

function outputPath(version: Version, region: Region, variant: Variant): string {
    return resolve(REPO_ROOT, `conf/${version}/${region}/${variant}.jsonc`);
}

// ---------------------------------------------------------------------------
// Emit: serialise SingBoxConfig → JSONC string with header
// ---------------------------------------------------------------------------

function header(version: Version, region: Region, variant: Variant): string {
    return [
        `// AUTO-GENERATED by scripts/generate.ts — do not edit by hand.`,
        `// Source: scripts/convention/intent/${region}.ts + scripts/convention/generator/*`,
        `// Regenerate: pnpm generate`,
        `// Variant: ${variant}   Version: ${version}   Region: ${region}`,
        `// CDN path: https://cdn.jsdelivr.net/gh/OneOhCloud/conf-template@dev/conf/${version}/${region}/${variant}.jsonc`,
    ].join('\n');
}

function emit(version: Version, region: Region, variant: Variant, config: SingBoxConfig): string {
    return `${header(version, region, variant)}\n${JSON.stringify(config, null, 4)}\n`;
}

// ---------------------------------------------------------------------------
// sing-box check (optional, --strict)
// ---------------------------------------------------------------------------

function findSingBoxBin(): string | null {
    if (process.env.SING_BOX_BIN) return process.env.SING_BOX_BIN;
    try {
        const out = execFileSync('which', ['sing-box'], {
            encoding: 'utf-8',
            stdio: ['ignore', 'pipe', 'ignore'],
        });
        const p = out.trim();
        return p.length > 0 ? p : null;
    } catch {
        return null;
    }
}

/**
 * Run `sing-box check` on a config with empty `auto.outbounds` / selector
 * outbounds patched to a stub direct node. The real on-disk file is never
 * touched — the patched copy is written to a temp file, checked, and
 * deleted.
 */
function singBoxCheck(bin: string, config: SingBoxConfig, label: string): void {
    const patched: SingBoxConfig = JSON.parse(JSON.stringify(config));
    const stubTag = '__onebox_check_stub__';
    for (const ob of patched.outbounds as any[]) {
        if (Array.isArray(ob.outbounds) && ob.outbounds.length === 0) {
            ob.outbounds = [stubTag];
        }
    }
    (patched.outbounds as any[]).push({ tag: stubTag, type: 'direct' });

    const tmp = mkdtempSync(join(tmpdir(), 'onebox-check-'));
    const tmpFile = join(tmp, 'config.json');
    writeFileSync(tmpFile, JSON.stringify(patched), 'utf-8');
    try {
        execFileSync(bin, ['check', '-c', tmpFile], { stdio: ['ignore', 'pipe', 'pipe'] });
    } catch (e: any) {
        const stderr = e?.stderr?.toString() ?? '';
        const stdout = e?.stdout?.toString() ?? '';
        throw new Error(`sing-box check failed for ${label}:\n${stderr || stdout || e?.message}`);
    } finally {
        rmSync(tmp, { recursive: true, force: true });
    }
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

type Generated = {
    version: Version;
    region: Region;
    variant: Variant;
    path: string;
    content: string;
    config: SingBoxConfig;
};

function main(): void {
    console.log(
        `[generate] ${DRY_RUN ? 'DRY RUN' : 'WRITE'}${STRICT ? ' + STRICT (sing-box check)' : ''}`,
    );
    console.log(`[generate] regions: ${REGIONS.join(', ')}`);
    console.log(`[generate] versions: ${VERSIONS.join(', ')}`);
    console.log(`[generate] variants: ${VARIANTS.join(', ')}`);
    console.log('');

    // Phase 1: build + validate everything in memory. Fail before any
    // file touches disk — a partial write would leave the repo in a
    // weird state.
    const generated: Generated[] = [];
    for (const version of VERSIONS) {
        for (const region of REGIONS) {
            for (const variant of VARIANTS) {
                const intent = INTENTS[region];
                const builder = GENERATORS[version];
                const config = builder(intent, variant);
                const label = `${version}/${region}/${variant}`;
                validate(config, variant, intent, label);
                const content = emit(version, region, variant, config);
                const path = outputPath(version, region, variant);
                generated.push({ version, region, variant, path, content, config });
                console.log(`  ✓ built + validated ${label}`);
            }
        }
    }

    // Phase 2: optional `sing-box check` on each (runs against in-memory
    // patched copies, not the on-disk files).
    if (STRICT) {
        const bin = findSingBoxBin();
        if (!bin) {
            console.error(
                `\n[generate] --strict requested but no sing-box binary found. ` +
                    `Set SING_BOX_BIN=/path or add sing-box to PATH.`,
            );
            process.exit(2);
        }
        console.log(`\n[generate] running sing-box check via ${bin}`);
        for (const g of generated) {
            const label = `${g.version}/${g.region}/${g.variant}`;
            singBoxCheck(bin, g.config, label);
            console.log(`  ✓ sing-box check ${label}`);
        }
    }

    // Phase 3: write to disk.
    if (!DRY_RUN) {
        for (const g of generated) {
            mkdirSync(dirname(g.path), { recursive: true });
            writeFileSync(g.path, g.content, 'utf-8');
        }
        console.log(`\n[generate] wrote ${generated.length} files`);
    } else {
        console.log(`\n[generate] dry run — ${generated.length} files NOT written`);
    }

    console.log('[generate] done');
}

try {
    main();
} catch (e: any) {
    if (e instanceof ValidationError) {
        console.error(`\n[generate] VALIDATION FAILED\n${e.message}`);
    } else {
        console.error(`\n[generate] ${e?.message ?? e}`);
        if (!(e instanceof ValidationError) && e?.stack) console.error(e.stack);
    }
    process.exit(1);
}
